### ISSUE TITLE
Documentation Improvement for Zipkin

### ISSUE THREAD

**Issue by rAun007** [rtyler/openzipkin#11]
Hi,

I have been using zipkin for almost like 2-3 months and I feel that the biggest hurdle in adoption is that documentation is missing and github pages doesn't have much as well.

Can somebody who knows in and out of the zipkin, can write documentation on the usage and the internals of the zipkin with the control levers that the user has along with recommended practices etc.

**Comment by eirslett** [comment]
This is a big issue for Zipkin, and probably the main reason people don't adopt it so easily.
Could you please elaborate a bit on what kind of documentation your are missing? (you already gave some examples) We could make a bullet point list and then break documentation into many smaller tasks.

**Comment by rtyler** [comment]
@rAun007  we've moved repos around a bit to make openzipkin/zipkin the canonical upstream, I've copied your ticket to openzipkin/zipkin#461
