### ISSUE TITLE
Add statsd type integration

### ISSUE THREAD

**Issue by jamescway** [rtyler/openzipkin#6]
I order to be have visibility into the health of the application it would be great to be able to record stats based on various metrics from within the application(s).  

This issue needs more thought in terms of:
 * which stats need to be collected
 * method of actual implementation
 * configuration methods

Will add more info later.

**Comment by eirslett** [comment]
By "the application", do you mean the applications you are tracing? Or the zipkin applications themselves, zipkin-collector/query/web?
We're already monitoring the zipkin services with statsd, but the code isn't fully open source yet. We just plugged a statsd shipper into Twitter's metering library, basically.

**Comment by rtyler** [comment]
@eirslett I believe @jamescway is referring to the type of work you may have already baked, and we might have some prototypes running around of.

Basically the expectation of production services from @Lookout is that they self-report metrics for health, etc. This ticket is about making sure that collector, query, etc are all instrumented properly

**Comment by rtyler** [comment]
openzipkin/zipkin#460
